sudo: required

services:
- docker

language: generic

jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t $DOCKER_USERNAME/go-meta-linter:`cat TAG` .
    - docker tag $DOCKER_USERNAME/go-meta-linter:latest
    - docker push $DOCKER_USERNAME/go-meta-linter:`cat TAG`
    - docker push $DOCKER_USERNAME/go-meta-linter:latest
